#
# SPDX-FileCopyrightText: Sebastiano Barezzi
# SPDX-License-Identifier: Apache-2.0
#

"preserve_hierarchy": false

files: [
	{
		"source": "/**/src/main/res/values/strings.xml",
		"translation": "/**/src/main/res/values-%android_code%/%original_file_name%",
		"languages_mapping": {
			"android_code": {
				"de": "de",
				"ru": "ru",
				"fr": "fr",
				"nb": "nb",
				"es-ES": "es"
			}
		},
	},
	{
		"source": "/fastlane/metadata/android/en-US/changelogs/*",
		"translation": "/fastlane/metadata/android/%locale%/changelogs/%original_file_name%",
	},
	{
		"source": "/fastlane/metadata/android/en-US/full_description.txt",
		"translation": "/fastlane/metadata/android/%locale%/full_description.txt",
	},
	{
		"source": "/fastlane/metadata/android/en-US/short_description.txt",
		"translation": "/fastlane/metadata/android/%locale%/short_description.txt",
	},
]
